<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
def matrix_mul(P, Q):
    num_rows_P = len(P)
    num_columns_P = len(P[0])
    num_rows_Q = len(Q)
    num_columns_Q = len(Q[0])
# To multiply an m×n matrix by an n×p matrix, the ns must be the same,and the result is an m×p matrix.
    if num_columns_P != num_rows_Q:
        print(
            "Matrix multiplication of two arguments not possible as number of columns in 1st Matrix is NOT Equal to the number of rows in 2nd Matrix")
        return
# Create an result matrix which will have dimensions of num_rows_P x num_columns_Q and fill this matrix with zeros
    result_matrix = [[0 for i in range(num_columns_Q)] for j in range(num_rows_P)]
# The element at row i, column j is the product of the ith row of matrix P and the jth column of matrix Q.
    for i in range(num_rows_P):
        for j in range(num_columns_Q):
            for k in range(num_columns_P):
# k-th column of P should be the k-th row of Q
                result_matrix[i][j] += P[i][k] * Q[k][j]
    return result_matrix
P = [[1, 3, 4],
     [2, 5, 7],
     [5, 9, 6]]

Q = [[1, 0, 0],
     [0, 1, 0],
     [0, 0, 1]]

R = [[1, 2],
      [3, 4]]

S = [[1, 2, 3, 4, 5],
      [5, 6, 7, 8, 9]]
             
T = [[1,2],
     [3,4]]
U = [[1,4],
     [5,6],
     [7,8],
     [9,6]]

print(matrix_mul(P, Q))
print(matrix_mul(R, S))
print(matrix_mul(T, U))

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]
[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]
Matrix multiplication of two arguments not possible as number of columns in 1st Matrix is NOT Equal to the number of rows in 2nd Matrix
None


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [4]:
import random
from bisect import bisect

def no_f_list(num_list, n=100):
    cumulative_sum_list = []
    j = 0
    for i in range(0, len(num_list)):
        j += num_list[i]
        cumulative_sum_list.append(j)

    result_list = []
    for _ in range(n):
        random_num = random.random()
        item_index = bisect(cumulative_sum_list, random_num * cumulative_sum_list[-1])

        result_list.append(num_list[item_index])

    return result_list

def sampling_based_on_magnitude(num_list):
    for i in range(1, 100):
        number = no_f_list(num_list)
        print(number)
A = [1, 5, 27, 6, 13, 28, 100, 45, 10, 79]



<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
def replace_d_h(str):
    replacements = [
        ('\D', '',),
        ('\d', '#'),
    ]

    for old, new in replacements:
        str = re.sub(old, new, str)
    return str
# Test-cases
A1 = "a2b3c4"
A2 = "234"
A3 = 'abc'
A4 = '#2a$#b%c%561#'
print(replace_d_h(A1))
print(replace_d_h(A2))
print(replace_d_h(A3))
print(replace_d_h(A4))

###
###

####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [5]:
import math
def show_dash_board(students,marks):

    marks_to_students_zipped = list(zip(marks, students))

    marks_to_students_zipped.sort(key=lambda item: item[0])

    top_5_ranks_by_marks = least_5_ranks_by_marks = marks_to_students_zipped

    if len(marks_to_students_zipped) > 5:
        top_5_ranks_by_marks = marks_to_students_zipped[:-6: -1]
       
        least_5_ranks_by_marks = marks_to_students_zipped[:5]

    students_between_25_and_75_percentile = marks_to_students_zipped[math.ceil(0.25 * len(marks_to_students_zipped)):
                                                                     math.floor(0.75 * len(marks_to_students_zipped))]

    return top_5_ranks_by_marks, least_5_ranks_by_marks, students_between_25_and_75_percentile


Students = ['student1', 'student2', 'student3', 'student4', 'student5', 'student6', 'student7', 'student8', 'student9',
            'student10']
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

show_dash_board(Students,Marks)


([(98, 'student8'),
  (80, 'student10'),
  (78, 'student2'),
  (48, 'student5'),
  (47, 'student7')],
 [(12, 'student3'),
  (14, 'student4'),
  (35, 'student9'),
  (43, 'student6'),
  (45, 'student1')],
 [(43, 'student6'), (45, 'student1'), (47, 'student7'), (48, 'student5')])

<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [ ]:
import math
def my_fun(S, P):
    total_list_of_closest_points_to_p = []
    result_closest_to_p = []

    for point in S:
        denominator = math.sqrt((point[0] ** 2) + (point[1] ** 2)) * math.sqrt((P[0] ** 2) + (P[1] ** 2))
        numerator = point[0] * P[0] + point[1] * P[1]

        if denominator != 0:
            cosine_distance_for_this_point = math.acos(numerator / denominator)
            total_list_of_closest_points_to_p.append((cosine_distance_for_this_point, point))

    for item in sorted(total_list_of_closest_points_to_p, key=lambda x: x[0])[:5]:
        result_closest_to_p.append(item[1])
    return result_closest_to_p


S = [(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
P = (3, -4)

closest_points = my_fun(S, P)
print(*[point for point in closest_points], sep="\n")

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [ ]:
import math
def my_fun(red, blue, line):
    sign_of_equation_with_red_point_tuple = -1

    if eval(line.replace('x', '*%s' % red[0][0]).replace('y', '*%s' % red[0][1])) > 0:
        sign_of_equation_with_red_point_tuple = 1

    for red_point in red:
        if sign_of_equation_with_red_point_tuple == 1 and eval(
                line.replace('x', '*%s' % red_point[0]).replace('y', '*%s' % red_point[1])) < 0:
            return 'NO'
        if sign_of_equation_with_red_point_tuple == -1 and eval(
                line.replace('x', '*%s' % red_point[0]).replace('y', '*%s' % red_point[1])) > 0:
            return 'NO'

    # Now the same set of two traversal for the blue-points tuples
    sign_of_equation_with_blue_point_tuple = -1 * sign_of_equation_with_red_point_tuple

    for blue_point in blue:
        if sign_of_equation_with_blue_point_tuple == 1 and eval(
                line.replace('x', '*%s' % blue_point[0]).replace('y', '*%s' % blue_point[1])) < 0:
            return 'NO'
        if sign_of_equation_with_blue_point_tuple == -1 and eval(
                line.replace('x', '*%s' % blue_point[0]).replace('y', '*%s' % blue_point[1])) > 0:
            return 'NO'

    return 'YES'

Red = [(1, 1), (2, 1), (4, 2), (2, 4), (-1, 4)]
Blue = [(-2, -1), (-1, -2), (-3, -2), (-3, -1), (1, -3)]

Lines = ["1x+1y+0", "1x-1y+0", "1x+0y-3", "0x+1y-0.5"]

for i in Lines:
    yes_or_no = my_fun(Red, Blue, i)
    print(yes_or_no)

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [2]:
def fun(x, a, b):
    if a == -1:
        v = int(x[b])/(b+1)
        for i in range(a+1,b+1):
            x[i] = v
    elif b == -1:
        v = int(x[a])/(len(x)-a)
        for i in range(a, len(x)):
            x[i] = v
    else:
        v = (int(x[a])+int(x[b]))/(b-a+1)
        for i in range(a,b+1):
            x[i] = v
    return x

def replace(text):
    # Create array from the string
    x = text.replace(" ","").split(",")
    # Get all the pairs of indices having number
    y = [i for i, v in enumerate(x) if v != '_']
    # Starting with _ ?
    if y[0] != 0:
        y = [-1] + y
    # Ending with _ ?
    if y[-1] != len(x)-1:
        y = y + [-1]    
    # run over all the pairs
    for (a, b) in zip(y[:-1], y[1:]): 
        fun(x,a,b)          
    return x

tests = [
    "_,_,_,24",
    "40,_,_,_,60",
    "80,_,_,_,_",
     "_,_,30,_,_,_,50,_,_"]

for i in tests:
    print (replace(i))

[6.0, 6.0, 6.0, 6.0]
[20.0, 20.0, 20.0, 20.0, 20.0]
[16.0, 16.0, 16.0, 16.0, 16.0]
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
def compute_conditional_probabilites(F, S):
    numerator = 0
    denominator = 0
    for i in range(len(T)):
        if(T[i][1] == S):
            denominator = denominator + 1
            if(T[i][0] == F):
                numerator = numerator + 1
    print('P(F = {} | S == {}) = {}/{}'.format(F, S, str(numerator), str(denominator)))
T = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
for i in ['F1', 'F2', 'F3', 'F4', 'F5']:
    for j in ['S1', 'S2', 'S3']:
        compute_conditional_probabilites(i,j)

P(F = F1 | S == S1) = 1/4
P(F = F1 | S == S2) = 1/3
P(F = F1 | S == S3) = 0/3
P(F = F2 | S == S1) = 1/4
P(F = F2 | S == S2) = 1/3
P(F = F2 | S == S3) = 1/3
P(F = F3 | S == S1) = 0/4
P(F = F3 | S == S2) = 1/3
P(F = F3 | S == S3) = 1/3
P(F = F4 | S == S1) = 1/4
P(F = F4 | S == S2) = 0/3
P(F = F4 | S == S3) = 1/3
P(F = F5 | S == S1) = 1/4
P(F = F5 | S == S2) = 0/3
P(F = F5 | S == S3) = 0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
def string_features(S1, S2):
    # Split the words of the sentences and put the words in a set
    S1_w = set(S1.split())
    S2_w = set(S2.split())
    # Use set intersection operation to get the common words between 2 sets and compute the length of the set
    a = len(S1_w & S2_w)
    # Use set difference operation to get the words that present in either of the set
    b = set(S1_w) - (set(S2_w))
    b1 = list(b)
    c = set(S2_w) - (set(S1_w))
    c1 = list(c)
    return a, b1, c1
S1 = "the first column F will contain only 5 uniques values"
S2 = "the second column S will contain only 3 uniques values"
a, b1, c1 = string_features(S1, S2)
print(a)
print(b1)
print(c1)

7
['5', 'first', 'F']
['3', 'second', 'S']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
from math import log
def compute_log_loss(L):
    loss = 0
    for row in L:
        loss += (row[0] * log(row[1], 10)) + ((1 - row[0]) * log(1 - row[1], 10))
        log_loss = -1 * loss / len(L)
    return log_loss

L = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(L)
print(loss)

0.42430993457031635
